### ISSUE TITLE
Kicad 6.99 - Viewport and Unit scaling issues

### ISSUE THREAD

**Issue by cchaine** [yaqwsx/PcbDraw#107]
Hi,

I have encountered this issue while trying to use PcbDraw with nightly version 6.99.0-3148-gdb6c153ad9-dirty of Kicad.

The unit conversion seems to be off when using the nightly build as the image is very small.

PR #106 should provide a workaround.

**Comment by yaqwsx** [comment]
We already support KiCAD 7 with PcbDraw 1, closing.
