### ISSUE TITLE
Kicad 6.99 - Wrong board outline

### ISSUE THREAD

**Issue by cchaine** [yaqwsx/PcbDraw#108]
Hi,

I have encountered this issue while trying to use PcbDraw with nightly version `6.99.0-3148-gdb6c153ad9-dirty` of Kicad.

The `board` layer is broken on the generated image.
<img src="https://user-images.githubusercontent.com/18381262/187475629-2a18dc6c-6808-4efe-83b3-495e42219446.png" width=25% height=25%>

There seem to be an issue with the `get_board_polygon` function. I rewrote the algorithm for that function which seemed to have fixed the issue.

PR #106 should fix this issue.

**Comment by yaqwsx** [comment]
I believe this was addressed in PcbDraw v1.
