### ISSUE TITLE
populate: highlighting rectangle is overlapping

### ISSUE THREAD

**Issue by dhaillant** [yaqwsx/PcbDraw#111]
Hello,
In populate, the highlighting rectangle is not centered around the component and is bigger than the component footprint, and then when two components are adjacent, the rectangles are overlapping.

![image](https://user-images.githubusercontent.com/11455430/188398727-8a992006-739e-4da5-97a9-933231221cc4.png)

pcbdraw, version 0.9.0+36.g7118c48

**Comment by yaqwsx** [comment]
Could you please test if the most recent version (with changes from today) fixes the problem?

**Comment by dhaillant** [comment]
Thank you for your help!
Indeed the offset is now gone. The red zone is now correctly centered around the component:
![image](https://user-images.githubusercontent.com/11455430/189604002-0baa0e57-51f3-42a8-8faa-d7e0a2ca0bc2.png)

However, the red zone is still a bit "too large" (I know this is a matter of taste probably), but as you can see on the picture above, when two adjacent components are to be populated in the same step, the red zone is overlapping and the color (as it's semi-transparent) is a bit darker on the overlap...

Then, on following steps, as the red zone overlaps adjacent components, it creates some visual confusion I think:
![image](https://user-images.githubusercontent.com/11455430/189604941-6a5d1b85-df8b-4118-a9d2-8930dd931c0a.png)

The components on this PCB are placed on a 2.54mm grid, so, pretty common spacing I guess.

So I'd like to know if there's a way to reduce the red zone size, or make it just the size of the footprint, please?

Thank you very much.

**Comment by yaqwsx** [comment]
The size is specified by the `highlight-padding` property of board style.

**Comment by dhaillant** [comment]
Thank you, that did the trick!
I first thought that the json style files were for the PCB rendering only and that populate wasn't concerned.
Thanks again!
