### ISSUE TITLE
Error: Invalid value for 'INPUT': File 'pcbdraw:\\UnoCh340.kicad_pcb' does not exist. 

### ISSUE THREAD

**Issue by AbdElhalim12** [yaqwsx/PcbDraw#115]
I got this error after typing the command: pcbdraw plot pcbdraw:\UnoCh340.kicad_pcb front.jpg
Error: Invalid value for 'INPUT': File 'pcbdraw:\\UnoCh340.kicad_pcb' does not exist.

**Comment by yaqwsx** [comment]
What does `pcbdraw:\UnoCh340.kicad_pcb` mean? It doesn't seem like a valid file path.

**Comment by AbdElhalim12** [comment]
the name of the folder that pcb file in, 
it in f:\pcbdraw\UnoCh340.kicad_pcb

**Comment by yaqwsx** [comment]
Yes, but you have to specify path to the file; `pcbdraw:\UnoCh340.kicad_pcb` is not a valid path; `f:\pcbdraw\UnoCh340.kicad_pcb` is.

**Comment by yaqwsx** [comment]
I consider this as resolved
