### ISSUE TITLE
Boards with complex outline renders broken

### ISSUE THREAD

**Issue by korken89** [yaqwsx/PcbDraw#129]
Hi, thanks for an awesome tool!

I've been using this tool to render PCBs for a while, and now I was going to start rendering my panels generated with KiKit.
However the panels comes out looking like below, but it works fine in KiCAD and it's 3D viewer (that is generally very sensitive to board edge errors).
So I'm quite sure the board edge is fine.

The generated panel is for a private board, but I can share it privately if it helps with debugging.

![image](https://user-images.githubusercontent.com/913109/195065014-b7c45f12-243b-4356-883a-c161cb09274b.png)

**Comment by yaqwsx** [comment]
You can share it privately via email: email@honzamrazek.cz. I will take a look at it and investigate what's wrong.

**Comment by yaqwsx** [comment]
The problem is not present in v1.0; the image was sent via e-mail.
