### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Andy79881** [yaqwsx/PcbDraw#134]
I would like to know the usage of the tool. The help tells me: pcbdraw plot [OPTIONS] INPUT OUTPUT.
What is INPUT and OUTPUT ? Sorry, if I missed the information here?

**Comment by marv** [comment]
There's a "Usage" section in the readme that should be helpful: https://github.com/yaqwsx/PcbDraw#usage

**Comment by Andy79881** [comment]
INPUT is the board file itself (*.kicad_pcb) . Even this may be self explonatory, it may be helpful to add this in the usage section. I have other issues with the tool and open dedicated issues.
