### ISSUE TITLE
Browser display issue, unexpected crop

### ISSUE THREAD

**Issue by adamws** [yaqwsx/PcbDraw#140]
Hi, I'm facing issues when displaying svg's generated by PcbDraw in web browsers. Files are ok when opened with inkscape.
I'm using Kicad 6.09 and PcbDraw 1.0.1

Take for example this svg file:
![width9](https://user-images.githubusercontent.com/12676586/221429916-9bea3b77-d841-4ec3-a2c5-bd4c46aa165f.svg)
there should be 9 elements in a row (github also renders 8 elements, at least for me)

This is how this looks in firefox v110:
![image](https://user-images.githubusercontent.com/12676586/221430105-15007ee8-b6c6-48ee-8a60-4f9dd81076a5.png)

and in chromium v109:
![image](https://user-images.githubusercontent.com/12676586/221430143-8738ef7c-05ef-4092-9f37-ebb967b73e1a.png)

I checked both windows and linux. I didn't check other browsers.

After download (in firefox `Save Image As` option) and open in inkscape, it is as expected:
![image](https://user-images.githubusercontent.com/12676586/221430276-e7aa075d-b9df-4ed8-beda-dfde8ebd5433.png)

I also attach pcb file which was used as input:
[width9.zip](https://github.com/yaqwsx/PcbDraw/files/10834471/width9.zip)

**Comment by yaqwsx** [comment]
This is how Google-chrome renders it: 

![Screenshot from 2023-02-26 20-08-02](https://user-images.githubusercontent.com/1590880/221431438-df75cb19-7a94-47fb-986b-56f3fab76e0e.png)

Could you try it once more with KiCAD 7? KiCAD 6 created SVG in KiCAD's native units (nm), and the browsers were confused by the huge numbers. KiCAD 7 instead uses mm, which should work everywhere.

**Comment by adamws** [comment]
KiCad 7 with PcbDraw 1.1.1 works as expected :+1:

**Comment by yaqwsx** [comment]
There isn't an easy fix for v6 and in the future, I would like to focus only on v7. Hence, closing.
