### ISSUE TITLE
[Feature request] get ride of whitespace on generated svg/png images with --margin 0 in case of option --no-components

### ISSUE THREAD

**Issue by nopeppermint** [yaqwsx/PcbDraw#151]
It would be nice if svg images generated with pcbdraw would automatically be limited to whitespace.

At the moment it do this with [inkscape](https://graphicdesign.stackexchange.com/questions/21635/getting-rid-of-whitespace-in-inkscape)

**Comment by set-soft** [comment]
Hi @nopeppermint ! 
Did you try `--margin`. If you are using KiBot: try with `size_detection` and you can also play with `margin`

**Comment by nopeppermint** [comment]
> Hi @nopeppermint ! Did you try `--margin`

yep, does not fully solve the issue (margin 0 only applied for one side of the picture):

without --margin:

![image](https://github.com/yaqwsx/PcbDraw/assets/3403218/46baceb1-e8a4-4769-b398-cd22f043bcb8)

with --margin 0
![image](https://github.com/yaqwsx/PcbDraw/assets/3403218/6163a0f3-a579-44f7-8942-409e1d851b59)

**Comment by nopeppermint** [comment]
inkscape -> File -> document properties -> resize to content creates then this:

![image](https://github.com/yaqwsx/PcbDraw/assets/3403218/a5da50ad-1723-49a5-a324-d3d7c2ff1057)

**Comment by set-soft** [comment]
Don't remember about the CLI interface, I no longer use it, but from KiBot you can:

1. You can specify individual margins for each side
2. Margins can be negative, removing extra space
3. You have more than one algorithm to determine the automatic margins

**Comment by yaqwsx** [comment]
@nopeppermint: margin should work. If it doesn't, it is a bug. Please include the source board and provide us with the precise steps to replicate.

**Comment by nopeppermint** [comment]
> @nopeppermint: margin should work.

I can confirm, it works with the Kicad Demo Project "Stickhub" but not with my Projects.
I will prepare a source board and steps to replicate

**Comment by nopeppermint** [comment]
[pcbdraw_example.zip](https://github.com/yaqwsx/PcbDraw/files/11868343/pcbdraw_example.zip)

I am using Kicad:

```
Application: KiCad x64 on x64

Version: 7.0.6-rc1-31-g7bcd3e2262, release build

Libraries:
	wxWidgets 3.2.2
	FreeType 2.12.1
	HarfBuzz 6.0.0
	FontConfig 2.14.1
	libcurl/7.88.1-DEV Schannel zlib/1.2.13

Platform: Windows 10 (build 19045), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jun 24 2023 05:13:33
	wxWidgets: 3.2.2 (wchar_t,wx containers)
	Boost: 1.81.0
	OCC: 7.6.3
	Curl: 7.88.1-DEV
	ngspice: 40
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:
	KICAD_SPICE=ON

```

To reproduce:
- open Kicad 7.0 Command prompt
- unzip this project
- navigate to it in the Kicad command prompt
- ```pcbdraw plot pcbdraw_example.kicad_pcb default.svg```
- ```pcbdraw plot --margin 0 pcbdraw_example.kicad_pcb default.svg```
- open the generated file in inkscape to compare:

![image](https://github.com/yaqwsx/PcbDraw/assets/3403218/ee8af7c1-ac4e-47cd-8ec7-ded0bb4d6ea6)
![image](https://github.com/yaqwsx/PcbDraw/assets/3403218/ede8930b-9994-4ae7-84c6-20b5932ea3a1)

**Comment by nopeppermint** [comment]
the png export seems to work without the need of --marking 0

![default](https://github.com/yaqwsx/PcbDraw/assets/3403218/7cfc3017-6862-49d2-ae02-4689e313e994)

**Comment by yaqwsx** [comment]
You have silkscreen outside the PCB edges (the dimensions). This silkscreen is taken into account when apply margin. However, it is hidden by PCB substrate mask. The cropping procedure doesn't interpret the masking (as it is quite challenging to implement properly).

I will think what we can do about this, but I suggest not placing dimensions into the silkscreen layer and use, e.g., `F.Fab` instead.

**Comment by yaqwsx** [comment]
> the png export seems to work without the need of --marking 0
> 
> ![default](https://user-images.githubusercontent.com/3403218/248786115-7cfc3017-6862-49d2-ae02-4689e313e994.png)

It behaves the same as SVG export:

![Screenshot from 2023-06-26 13-56-31](https://github.com/yaqwsx/PcbDraw/assets/1590880/9ae36f16-e3d5-488d-b9ed-ec976705e116)

**Comment by nopeppermint** [comment]
> It behaves the same as SVG export:

indeed, I just double checked in gimp :-(

**Comment by yaqwsx** [comment]
It's exactly the same problem - we consider all geometry, but we ignore the masking at the moment.

**Comment by set-soft** [comment]
> pcbdraw_example.zip

Using KiBot config:

```yaml
kiplot:
  version: 1

outputs:
  - name: PcbDraw
    comment: "PcbDraw test top"
    type: pcbdraw
    dir: PcbDraw
    options: &pcb_draw_ops
      format: svg
      warnings: none
      margin: -0.1

  - name: PcbDraw2
    comment: "PcbDraw test bottom"
    type: pcbdraw
    dir: PcbDraw
    options:
      <<: *pcb_draw_ops
      bottom: True
```

I get:
![pcbdraw_example-bottom](https://github.com/yaqwsx/PcbDraw/assets/22823627/a5d67586-c9e1-4b78-9832-928d768d0f7a)
![pcbdraw_example-top](https://github.com/yaqwsx/PcbDraw/assets/22823627/19a0201a-6c54-45a3-a217-1e75118b99c8)

The small 0,1 mm margin is removed.
I think the problem with the standalone PcbDraw is that its trying to be "smart" and use a very complicated mechanism that involves SVG Path. But just asking KiCad which is the Bounding Box solves the problem. KiBot defaults to the KiCad mechanism, but you can ask for the SVG Path thing. KiCad knows how to clip the castellated pads.

**Comment by yaqwsx** [comment]
The reason why we do it this way is that we don't want to crop components that might stick out of the PCB outline. We primarily use PcbDraw for drawing boards **with** components, not bare-bone PCBs.

The suitable algorithm might be to collect the PCB boundary from KiCAD, collect bounding boxes of all components from SVG, and combine them.

**Comment by nopeppermint** [comment]
>  drawing boards with components, not bare-bone PCBs.

yes, but as far as I understand I would have to generated for each footprint an svg file as I use non of the footprints in the kicad library, all are custom..

If I run:

```
pcbdraw plot --margin 0 --no-components pcbdraw_example.kicad_pcb default.svg
```
there are no components which can be crop (as there are no-components) but the result is still the same

**Comment by nopeppermint** [comment]
> 



> 



> Using KiBot config:
> 
> ```yaml
> kiplot:
>   version: 1
> 
> outputs:
>   - name: PcbDraw
>     comment: "PcbDraw test top"
>     type: pcbdraw
>     dir: PcbDraw
>     options: &pcb_draw_ops
>       format: svg
>       warnings: none
>       margin: -0.1
> 
>   - name: PcbDraw2
>     comment: "PcbDraw test bottom"
>     type: pcbdraw
>     dir: PcbDraw
>     options:
>       <<: *pcb_draw_ops
>       bottom: True
> ```
> 
> I get: ![pcbdraw_example-bottom](https://user-images.githubusercontent.com/22823627/248808839-a5d67586-c9e1-4b78-9832-928d768d0f7a.svg) ![pcbdraw_example-top](https://user-images.githubusercontent.com/22823627/248808845-19a0201a-6c54-45a3-a217-1e75118b99c8.svg)
> 
> The small 0,1 mm margin is removed. I think the problem with the standalone PcbDraw is that its trying to be "smart" and use a very complicated mechanism that involves SVG Path. But just asking KiCad which is the Bounding Box solves the problem. KiBot defaults to the KiCad mechanism, but you can ask for the SVG Path thing. KiCad knows how to clip the castellated pads.

pcbdraw plot does not accept a margin of -0.1:


```
pcbdraw plot --margin -0.1 pcbdraw_example.kicad_pcb default.svg
Usage: pcbdraw plot [OPTIONS] INPUT OUTPUT
Try 'pcbdraw plot --help' for help.

Error: Invalid value for '--margin': '-0.1' is not a valid integer.
```

**Comment by yaqwsx** [comment]
> there are no components which can be crop (as there are no-components) but the result is still the same

Urg, I am just trying to explain how the current algorithm works, and why it was designed in such a way. Yes, there are limitations you run into (and we didn't consider them back then as an issue). It needs to be reworked (just like I proposed above). It will be done, sometimes. At the moment, I cannot promise you any particular timeline for the implementation.

> yes, but as far as I understand I would have to generated for each footprint an svg file as I use non of the footprints in the kicad library, all are custom..

That's kind of the point of PcbDraw - to create stylized drawings of the boards that are nice. This is why we use the hand-draw library of components - to keep them stylized. If you just want a faithful representation of the board with components, I suggest using `pcbdraw render` that just captures the 3D-rendered board and uses 3D models. Also, KiBot provides a pipeline to export 3D model and render it via Blender, IIRC. That might be also a viable path for you.

**Comment by nopeppermint** [comment]
>  It will be done, sometimes. At the moment, I cannot promise you any particular timeline for the implementation.

No worries, I didn't wanted to attack you, I will change it back to a "Feature Request" and thanks for the explanations.

> pcbdraw render that just captures the 3D-rendered board and uses 3D models.

I know, but I am on windows -> not supported..

I will try Kibot.

**Comment by yaqwsx** [comment]
> I know, but I am on windows -> not supported..
> 
> I will try Kibot.

Well, KiBot has the same problem. Nevertheless, both tools are designed for automated processing in CI, where Linux shouldn't be a problem. If you want to just get a picture of the PCB, why not just render it manually inside KiCAD's 3D view and save the picture?

**Comment by yaqwsx** [comment]
I made changes to the algorithm for building bounding boxes in [0a137fe](https://github.com/yaqwsx/PcbDraw/commit/0a137fe1d82eefb7e8c1ceacd642d14f13fcde44). It should resolve all issue you observe.
