### ISSUE TITLE
Idea for a script

### ISSUE THREAD

**Issue by leoheck** [yaqwsx/PcbDraw#19]
I have an idea for a script to generate SVG files easily. At least the initial version of them.

The script can use the 3d models of each footprint (.step files) to export a top view of the model in SVG format. It will be really good because it can generate a file for each footprint that misses the SVG view automatically. So, if the user wants something better he just has to open the file and improve the vector.

**Comment by CornyjK** [comment]
#9

**Comment by yaqwsx** [comment]
Duplicate #9
