### ISSUE TITLE
Solve Windows compatibility

### ISSUE THREAD

**Issue by yaqwsx** [yaqwsx/PcbDraw#23]
Currently, PcbDraw has a dependency on several Python libraries. This is a problem on Windows, where KiCAD brings its own, binary incompatible, version of Python - the dependencies cannot be installed (it would be necessary to compile them using Msys2).

The proposed solution - split PcbDraw into two executables - the first one, with no dependencies, exports all necessary data from KiCAD to files, the second one (with Python dependencies) finishes the work. There will be a wrapper to automate the process; on Windows, it will run the first step using the KiCAD's Python, the second step is executed via system Python. This also solves the problem with Python2 compatibility on Windows - it should be fairly easy to write a Python2 compatible first stage.

**Comment by D-Maker** [comment]
When I run the pcbdraw command of windows 10 an Error like this pops up: 
`    'Try to install:\n  ' + msg)
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  http://docs.wand-py.org/en/latest/guide/install.html#install-imagemagick-on-windows`

still doesn't work after installing image magick and restarting the same error appears...

**Comment by yaqwsx** [comment]
I am aware of the problem, unfortunately, I am not able to solve without KiCAD migrating to Python 3 - which should happen with KiCAD 6 release.

**Comment by yaqwsx** [comment]
KiKit already works on Windows with KiCAD nightly. The installation is a little clumsy, but we will provide clear instructions once stable version is released.

**Comment by mikelemo** [comment]
> KiKit already works on Windows with KiCAD nightly. The installation is a little clumsy, but we will provide clear instructions once stable version is released.

Huh ok cool I'll be giving it a try soon! wonder when kicad 6 be out...

**Comment by yaqwsx** [comment]
Unfortunately, the panelization still does not work as KiCAD 6 misses some essential parts of API we rely on.

**Comment by yaqwsx** [comment]
With KiCAD 6 release, this is no longer relevant.
