### ISSUE TITLE
Wrong rotation of pad with oval shape 

### ISSUE THREAD

**Issue by JarekParal** [yaqwsx/PcbDraw#24]
PcbDraw generates pictures with a wrong rotation of pad with oval shape:
![YellowMotorEncoder-front](https://user-images.githubusercontent.com/6726556/85594507-47fec180-b648-11ea-8a01-5438f88ce624.png)

In Kicad both of the holes have the same direction. But:
- top has rotation = 0, x = 0.8, y = 5.5
- bottom has rotation = -90, x = 5.5, y = 0.8
![image](https://user-images.githubusercontent.com/6726556/85594745-7a102380-b648-11ea-9edc-255f51dbecef.png)

Original file which was used as input for KiKit web page command:
[YellowMotorEncoder_board.zip](https://github.com/yaqwsx/PcbDraw/files/4826703/YellowMotorEncoder_board.zip)

**Comment by JarekParal** [comment]
You can test fix on the YellowMotorEncoder board: https://roboticsbrno.github.io/RB0003-YellowMotorEncoder/

**Comment by yaqwsx** [comment]
Fixed in f231ac2
