### ISSUE TITLE
Board edge recognition issues

### ISSUE THREAD

**Issue by kwendenarmo** [yaqwsx/PcbDraw#3]
I just tried this great tool, and I've found some flaws:

-   The board edge is not respected: The copper outside the board edge should be removed. For example in edge connectors.
-   With irregular board shapes, the mask is not painted correctly, (currently off the board).

The image is the copper layer (top) and the board edge along the soldermask (below). You can see these faults:

![imagen](https://cloud.githubusercontent.com/assets/1426137/25541729/163530b0-2c50-11e7-9b1b-4043be6ee5de.png)

**Comment by yaqwsx** [comment]
Could you send me a KiCAD board to reproduce this issue?

**Comment by kwendenarmo** [comment]
Of course, you can find it in https://github.com/akornsys-rdi/USB-power-dist

**Comment by yaqwsx** [comment]
Thanks, I'll try to look at it in the next few days.

**Comment by yaqwsx** [comment]
PcbDraw produced invalid SVG files (integers were formatted as floats) and some editors have trouble to render them correctly. The problem is fixed and I also added support for rendering through-hole pads. Now your board looks like this:

![board](https://cloud.githubusercontent.com/assets/1590880/25716002/ce829fb6-30fd-11e7-898b-3b57961e6868.png)

**Comment by kwendenarmo** [comment]
Awesome, great job! The "male" edge conector on the right of the board do not appear as copper (without soldermask). Is the exported image problem or does it not recognize it as a pad?

**Comment by yaqwsx** [comment]
The reasons for that is that KiCAD export these two pads as an SVG path, which is for no obvious reasons properly handled. I could transform the paths to a polyline, but first I would like to spend some time for  finding the true root of problems. If I cannot solve it, I'll implement the transformation.

**Comment by yaqwsx** [comment]
It should be fixed now.

**Comment by kwendenarmo** [comment]
wonderful! I'll try it as soon as I can! Really great job!
