### ISSUE TITLE
Rare YAML parser

### ISSUE THREAD

**Issue by set-soft** [yaqwsx/PcbDraw#34]
The current setup uses `pyaml` package, this is: [Pretty YAML](https://pypi.org/project/pyaml/)

This is a version of the popular `PyYAML` package ( [PyYAML](https://pypi.org/project/PyYAML/) ) modified to emit prettier YAML.

But PcbDraw only parses YAML, never dumps it. So I don't see the point of using a rare dependency.

To illustrate my point, according to Debian voting system `PyYAML` has 26925 installations and 12527 votes. Which far more than what `pyaml` has: 58 installations and 4 votes.

I sugest replacing **pyaml** by **pyyaml** in `setup.py`

**Comment by yaqwsx** [comment]
You are right. The dependency was changed in d20258f
