### ISSUE TITLE
Obsolete argparse dependency

### ISSUE THREAD

**Issue by set-soft** [yaqwsx/PcbDraw#35]
The current *setup.py* asks for [`argparse`](https://pypi.org/project/argparse/) package.

But this functionality became part of standard Python on v3.2. The current version is 3.8.3, and even the conservative Debian stable is using 3.7.3 (released on march 2019). Python 3.2 was released in february 2011.

So I think this dependency isn't really needed. I guess it got there when PcbDraw was Python 2, but for Python 3 there is no need to install `argparse` as a separated package.

BTW: I'm currently using [`docopt`](https://pypi.org/project/docopt/), well in fact a [patched version](https://github.com/INTI-CMNB/kiplot/blob/master/kiplot/docopt.py) to support args.*argument* (in addition to args["*argument*"]). This package gets the command line specification from the doctring.

**Comment by yaqwsx** [comment]
You are right, fixed in d20258f

About docopt - I prefer to use click in my other projects. Unfortunately, when I wrote the first version of PcbDraw, I wasn't aware about it. That's why I used argparse.
