### ISSUE TITLE
EdgeCut detection not working properly

### ISSUE THREAD

**Issue by kb-elmo** [yaqwsx/PcbDraw#44]
I stumbled upon this really weird issue yesterday where some edgecuts are apparently not fully recognized and are not properly cut out of the PCB substrate layer

![](https://i.imgur.com/SSBKYKe.png)

It works perfectly fine in KiCADs own 3D renderer and when exported as gerber files it is rendered correctly in other viewers (like tracespace) too.

So far I couldn't find anything wrong with those edgecuts in the kicad files itself when compared to the other working edgecuts.

The file that I'm trying to render is this one:   
https://raw.githubusercontent.com/kb-elmo/sesame/master/extras/switchplate.kicad_pcb

**Comment by yaqwsx** [comment]
Fixed in 7435dea5034027b9f8bf9e169fc57ef91cad0346 (part of v0.6.0 release)

**Comment by kb-elmo** [comment]
Thanks! 😃
