### ISSUE TITLE
Default configuration file

### ISSUE THREAD

**Issue by kwendenarmo** [yaqwsx/PcbDraw#5]
It would be very nice to have a configuration file (json type or any other) with the default path of the style file and library path, which would be used in case of not providing any path as an argument.
This would greatly simplify the invocation of the PcbDraw command

Thanks

**Comment by yaqwsx** [comment]
I have decided to make the style as an optional argument with a fallback to default green style. This should simplify usage in most of the use cases of PcbDraw. Invoking a default file seems rather confusing to me.
