### ISSUE TITLE
Kicad nightly (5.99)

### ISSUE THREAD

**Issue by perigoso** [yaqwsx/PcbDraw#70]
Having trouble generating for nightly projects, i was under the impression specifying the python path was enough, but I'm getting this error:
```
Traceback (most recent call last):
  File "/usr/bin/pcbdraw", line 33, in <module>
    sys.exit(load_entry_point('PcbDraw==0.6.1', 'console_scripts', 'pcbdraw')())
  File "/usr/lib/python3.9/site-packages/pcbdraw/pcbdraw.py", line 793, in main
    board_cont.append(get_board_substrate(board, style, not args.no_drillholes, args.back))
  File "/usr/lib/python3.9/site-packages/pcbdraw/pcbdraw.py", line 433, in get_board_substrate
    popt.SetTextMode(pcbnew.PLOTTEXTMODE_STROKE)
AttributeError: module 'pcbnew' has no attribute 'PLOTTEXTMODE_STROKE'
```
Is this due to some api change?

version `5.99.0_12876_gfb5fef9f5f`

**Comment by yaqwsx** [comment]
This is due to API change. I plan to revisit the changes in nightly soon, however, I can't promise you any deadline.

**Comment by perigoso** [comment]
I was trying to use a system install of this, through the arch repository, when i cloned and ran the script directly i was able to generate, so i don't think the issue is an api change after all

**Comment by yaqwsx** [comment]
The compatibility with nightly was introduced in version 0.8. I just noticed from your log that you used version 0.6.1. Please, install the recent stable version (e.g., from pip).
