### ISSUE TITLE
Drill holes supported?

### ISSUE THREAD

**Issue by NT7S** [yaqwsx/PcbDraw#8]
Are drill holes supported by PcbDraw? I'm not seeing any rendered in the drawings I generate, but I wasn't certain if that is a bug or something not yet supported.

Thank you again for the fantastic tool!

**Comment by yaqwsx** [comment]
They are not supported (yet) as KiCAD plotting Python API cannot plot holes. The alternative is to walk through the components, detect holes and draw, however I haven't implemented that yet..

**Comment by NT7S** [comment]
I don't know much about the KiCad API, so I appreciate the clarification.

**Comment by yaqwsx** [comment]
I implemented the support for drill holes in 2d5076b:
![test svg](https://user-images.githubusercontent.com/1590880/26977952-f2089d12-4d29-11e7-9c6c-85cff7619be8.png)

**Comment by NT7S** [comment]
Works like a charm here, thank you so much for this.
