### ISSUE TITLE
PCBDraw does not account for the soldering paste

### ISSUE THREAD

**Issue by joric** [yaqwsx/PcbDraw#85]
I want to know where I have soldering paste on the PCB. Kicad 3d view shows that, KicadScripts support that, how to do the same in PCBDraw? KicadScripts example output (note SMD pads are silver but the through-holes are golden):

![nrfmicro-Front](https://user-images.githubusercontent.com/852547/147896737-9a2ea874-41ee-4058-bd74-9e6e117f5cdd.png)

**Comment by yaqwsx** [comment]
At the moment, PcbDraw doesn't support the paste layer. The original motivation for PcbDraw is to create a nice drawing of the board, e.g., for pinout diagrams. Therefore, having a paste layer seemed unnecessary. 

If there are valid use-cases for having SMD pads rendered differently, we can add such a feature. But I don't want to implement a feature with limited use-case.

Nevertheless, if you submit a PR adding this feature, I will be happy to accept it. You basically have to modify the function `get_board_substrate` an extend the plot plan.

**Comment by joric** [comment]
The valid case is a board preview in presentation, seeng soldering paste helps to spot issues and fix the board. I'll see what I can do. It perhaps would require fixing json templates and adding another entry (or maybe not ultimately, since all soldering paste is grey).

**Comment by yaqwsx** [comment]
An update: I am considering a major rewrite of PcbDraw that should allow for custom plot plans. This would nicely address this feature request.

**Comment by yaqwsx** [comment]
Implemented in fead173.
