### ISSUE TITLE
KiCAD 6.0 vias rendered as silkscreen

### ISSUE THREAD

**Issue by kb-elmo** [yaqwsx/PcbDraw#88]
It seems that PCBdraw is rendering vias from KiCAD 6 files as silkscreen now.

Tested it by setting the silkscreen color to red and got this as a result.
![pcb_render](https://i.imgur.com/7wUCjwZ.png)

Is this intentional?
Imho it does look kind of weird when all the vias are white.

Ideally they should have the color of the board.

**Comment by yaqwsx** [comment]
Could you provide me with the source board so I can test it and debug it?

**Comment by kb-elmo** [comment]
The problem happened on every KiCAD 6 PCB that I tested so far.

But here's the file that I used for the render above: [pcb.zip](https://github.com/yaqwsx/PcbDraw/files/7874704/pcb.zip)

**Comment by yaqwsx** [comment]
I traced it that there is indeed a change in KiCAD 6 where the vias are included in generated SVG silkscreen files. However, I wasn't able to locate which settings cause that.

**Comment by Electro707** [comment]
What's strange is that using KiCAD's built in SVG exporter, which uses the same class as pcbdraw fundamentally from what I could tell from KiCAD's code, exporting only the silkscreen layer doesn't show any vias:
![image](https://user-images.githubusercontent.com/15680882/150667266-8b6d5a7f-f113-4f06-b068-709e63e35141.png)

**Comment by Electro707** [comment]
Another thing I noticed is the exported from KiCAD's plotter directly colors vias white, while actual silkscreen black
![image](https://user-images.githubusercontent.com/15680882/150667917-d3a4907b-fa0c-4d14-9fb1-0c60ded43a94.png)
![image](https://user-images.githubusercontent.com/15680882/150667962-d0e9fa33-ee21-4609-a08f-84a57684f4d0.png)

**Comment by yaqwsx** [comment]
Oh, sorry, I didn't post it here. This is definitely a bug in KiCAD, I opened an issue for that a few days ago: https://gitlab.com/kicad/code/kicad/-/issues/10491

We could make a work-around, but I would (slightly) prefer a fix in KiCAD.

**Comment by yaqwsx** [comment]
Since the bug got low-priority I guess it won't be fixed until v7 (with the new API). Therefore, I implemented a workaraund in f1b0873.

**Comment by kb-elmo** [comment]
Thanks! 😄
