### ISSUE TITLE
[Feature Request] Clip silkscreen on pads

### ISSUE THREAD

**Issue by duckyb** [yaqwsx/PcbDraw#95]
It would be nice to have the option to remove silkscreen from pads and holes, as seen here:

![plate](https://user-images.githubusercontent.com/27895007/168818632-911e1308-be9c-484c-ae81-f29b274d17b0.png)

**Comment by yaqwsx** [comment]
This is already implemented in master, and it will be part of the v1 release:
![Screenshot from 2022-05-17 15-18-38](https://user-images.githubusercontent.com/1590880/168820339-a5ef28ed-c402-4091-9d83-c7cba6dc5ad9.png)
![test](https://user-images.githubusercontent.com/1590880/168820342-d29499d7-dd67-4bd3-81e3-821e4cf4af57.png)
